### ISSUE TITLE
Add an EvmProvider

### ISSUE THREAD

**Issue by ClementWalter** [the-candy-shop/starksheet-monorepo#42]
## Context

The webapp relies on a [`chainProvider`](../blob/packages/starksheet-webapp/src/provider/chainProvider.ts) to interact with the underlying blockchain it targets. Currently, only a [`starknetProvider`](../blob/packages/starksheet-webapp/src/provider/starknetProvider.ts) is implemented. To be able to target an EVM chain, we need to add an `evmProvider`.

## Task

- [ ] Update the `chainProvider.ts` interface so that precise types are returned (and not `any`)
- [ ] Create a `evmProvider.ts` file next to the `starknetProvider.ts`
- [ ] Implement the `ChainProvider` interface using `ethers.js`

## Comments

The types currently returned are defined in starknet-js. I am not sure how EVM and Starknet types overlaps, but we need to have a standard types for both that it consumed by the rest of the application.

Consequently, it's probably necessary to create our types for the return type of the interface. 
These types shall be put in a new file in `src/types/provider.ts`

**Comment by robinstraub** [comment]
I can work on this
