### ISSUE TITLE
Get chainId from the RPC

### ISSUE THREAD

**Issue by ClementWalter** [the-candy-shop/starksheet-monorepo#43]
## Context

Currently, the [`chainId`](../blob/packages/starksheet-webapp/src/provider/index.ts) const is hardcoded in a file. Since only Starknet was targeted, the app was parametrized with a keyword (mainnet, testnet, devnet). This was fine when only Starknet chain was targeted but we now need to have everything parametrized by the selected RPC endpoint. Every chain, being Starknet or EVM based, mainnet or testnet, is indeed fullu characterize from the dapp point of view by provided RPC endpoint. (Note: the starknet gateway is about to be deprecated and the RPC, also for Starknet, will be the only source of truth).

## Task

- [ ] Refacto the [index.ts](../blob/packages/starksheet-webapp/src/provider/index.ts) file to derive everything from one single a `REACT_APP_RPC_NODE_URI` env variable
- [ ] Add the `chainId` method in the chainProvider interface and implement it for both the EVM and the Starknet provider
- [ ] Create a `STARKNET_CHAIN_IDS = [ ... ]` const to store the chain Ids related to Starknet
- [ ] move the `ethChainId` const from [index.ts](../blob/packages/starksheet-webapp/src/provider/index.ts) to the [`Widget.ts`](../blob/packages/starksheet-webapp/src/components/Widget/Widget.tsx)
- [ ] Hide the Widget if chainIds not in Starknet chain ids
- [x] Create a custom hook for retrieving the `chainProvider` instead of having it hardcoded

**Comment by robinstraub** [comment]
I can work on this

**Comment by ClementWalter** [comment]
Because I'm not an expert in React hooks, I don't know how to best make this "async new" work. The idea is: at initialization, from a given RPC url:
- call RPC method `starknet_chainId`, if it works, get chainId and instantiate starknetProvider
- if it fails, call `eth_chainId`, if it works, get chainId and instantiate evmProvider
- if it fails, raise error
