### ISSUE TITLE
Add class Evmsheet in useOnsheetContract hook

### ISSUE THREAD

**Issue by ClementWalter** [the-candy-shop/starksheet-monorepo#44]
## Context

The Onsheet contract (starksheet named is a deprecated name since the app now doesn't target only starknet) is the main contract deploying sheet. It could be seen as the pendant of a spreadsheet that actually owns several sheets.

We need to add a EvmContract implementation of the Onsheet contract interface.

## Task

- [ ] Move the `StarksheetContract` from [the hook](../blob/packages/starksheet-webapp/src/hooks/useOnsheetContract.ts) to a new `src/contracts/onsheet/starksheet.ts` file and import it in the hook
- [ ] Add a `EvmsheetContract` and implement the interface
- [ ] In the hook, use the chainId and STARKNET_CHAIN_ID to return either a Starksheet or a Evmsheet contract

**Comment by robinstraub** [comment]
I can work on this
