### ISSUE TITLE
Add class EvmSheetContract in useSheetContract hook

### ISSUE THREAD

**Issue by ClementWalter** [the-candy-shop/starksheet-monorepo#45]
## Context

See #44 

## Task

See also #44 

- [ ] Move the class `StarknetSheetContract` into a new file `src/contracts/sheet/starknetSheet.ts`
- [ ] Implement the `SheetContract` for the Evm
- [ ] In the hook, use the chainId and STARKNET_CHAIN_ID to return one contract or another

**Comment by robinstraub** [comment]
I can work on this
